// Telling a forwarder their letter arrived.
//
// This is the only outward sign that anything happened. Somebody forwards a
// letter to `post@`, and until now the entire visible result was nothing: no
// reply, no receipt, and a website they may not have an account on. The two
// failure modes that produces are opposite and both bad -- they assume it
// worked when it did not, or they forward the same letter four more times
// because they cannot tell that it did.
//
// **It answers a message, and never fires on a schedule.** Everything in this
// file is a reply to mail its recipient sent us seconds earlier, which is what
// keeps it correspondence rather than a mailing list, and it carries
// `Auto-Submitted: auto-replied` so nothing on the other side answers it back.
//
// **One per person per archive per day, however many letters they send.** The
// gate is the point: the scenario this has to survive is a family finding the
// service and forwarding two years of letters in one sitting, which is a
// behaviour the pipeline was explicitly built to welcome. A hundred receipts
// for that is not a courtesy, it is what the recipient's mail provider will
// reasonably conclude is an attack. So the message says the archive has the
// letters rather than counting them, which is both truer and cheaper than
// tallying a session whose end we cannot detect.
//
// **Stored and duplicate are the same news.** A letter that deduped against
// one somebody else already forwarded is *in the archive*, which is the only
// thing the sender wanted to know. Distinguishing them would mean explaining
// dedup to somebody who has no idea anyone else forwarded anything, and the
// honest summary of both is the same sentence.
//
// **It threads.** `In-Reply-To` and `References` name the message we were
// sent, so the receipt lands under the forward in the sender's own client
// rather than arriving as an unrelated message from a service they have never
// signed into. Our own `Message-ID` is generated by Cloudflare on a Cloudflare
// domain and cannot be set, so an inbound id is the only handle threading ever
// gets -- see `receivedMessageId` in ingest.js.

import { escapeHtml as escape, HUMAN_ADDRESS, mailFrom } from './mail.js';
import { POST_ADDRESS } from './offer.js';
import { recordDelivery } from './delivery.js';
import { optedOut } from './optout.js';
import { TABLES } from './tables.js';


const day = (at) => at.toISOString().slice(0, 10);

/**
 * The message body. Exported so its wording is testable without a mailer.
 *
 * DRAFT COPY, like the other replies.
 *
 * **It does not name the missionary in the subject line**, which is visible on
 * a lock screen, and does name them in the body, which is not -- the same split
 * the nudge makes, for the same reason. The recipient put that name in the mail
 * they just sent us, so the body discloses nothing they do not already know.
 *
 * **The link is offered without promising it will work.** A forwarder is very
 * often not a member of the archive, and sending them to a page that will ask
 * them to sign in and then refuse them would turn a receipt into a rejection.
 * So the sentence is about where the letters now live, not an invitation to go
 * and read them.
 */
export function ackEmail({ author, slug, baseUrl }) {
    const root = String(baseUrl ?? '').replace(/\/$/, '');
    const url = `${root}/${encodeURIComponent(slug)}/`;
    const from = author ? ` from ${author}` : '';

    const subject = 'Your letter arrived';

    const text = [
        `Thank you — the letter${from} you forwarded is in the archive.`,
        '',
        'You do not need to do anything else, and you do not need to send it',
        'again. If you forwarded several letters at once, they are all there;',
        'this is one note rather than one per letter.',
        '',
        'The archive is here, for anyone who has been given access to it:',
        '',
        `   ${url}`,
        '',
        'If you were not expecting this, someone forwarded a letter to us from',
        'your address. Nothing was published anywhere public, and you can',
        'reply to this message and a person will read it.'
    ].join('\n');

    const html = [
        `<p>Thank you &mdash; the letter${from ? ` from ${escape(author)}` : ''} you forwarded is in the archive.</p>`,
        '<p>You do not need to do anything else, and you do not need to send it again. If you forwarded several letters at once, they are all there; this is one note rather than one per letter.</p>',
        `<p>The archive is here, for anyone who has been given access to it: <a href="${escape(url)}">${escape(url)}</a></p>`,
        '<p>If you were not expecting this, someone forwarded a letter to us from your address. Nothing was published anywhere public, and you can reply to this message and a person will read it.</p>'
    ].join('\n');

    return { subject, text, html };
}

/**
 * Acknowledge a forward, at most once a day per person per archive.
 *
 * Returns a status rather than throwing, and the caller swallows even that.
 * The letter is already committed and archived by the time this runs; there is
 * no version of "the receipt failed" that justifies making the sender's mail
 * server deliver the letter a second time.
 *
 * @param {object} input
 * @param {object} input.tables
 * @param {object} input.mailer
 * @param {string} input.to         the forwarder, already DMARC-authenticated
 * @param {string} input.slug
 * @param {string} [input.author]   the missionary the letter was from
 * @param {string} [input.baseUrl]
 * @param {string} [input.messageId] `Message-ID` of the forward being answered
 */
export async function acknowledgeForward({
    tables,
    mailer,
    to,
    slug,
    author = '',
    baseUrl = '',
    messageId = '',
    now = () => new Date(),
    log = console
}) {
    if (!tables || !mailer || !to || !slug) return { status: 'skipped' };

    const recipient = String(to).toLowerCase();

    // Checked even though this is a reply. An opt-out here is unusual and
    // specific -- somebody who forwards letters and does not want to be
    // thanked for it -- and it is exactly the kind of request that is easy to
    // honour and inexcusable to lose.
    if (await optedOut({ tables, email: recipient })) {
        log.info?.('ack: recipient has opted out, staying quiet', { slug });
        return { status: 'optedout' };
    }

    // Same gate as the nudge: an insert that loses the race returns falsy, so
    // the row is both the record and the lock. Keyed by the UTC day for the
    // same reason the daily cap is -- a day boundary that moves with the
    // sender's timezone is worse than one in the wrong place.
    const first = await tables.insertEntity(TABLES.nudges, {
        partitionKey: recipient,
        rowKey: `ack:${slug}:${day(now())}`,
        sentAt: now().toISOString()
    });

    if (!first) {
        log.info?.('ack: already thanked today, staying quiet', { slug });
        return { status: 'duplicate' };
    }

    const body = ackEmail({ author, slug, baseUrl });
    const result = await mailer.send({
        // The address they wrote to, because Gmail weighs prior
        // correspondence and a receipt arriving from somewhere else reads as
        // an unrelated stranger. `Reply-To` is what stops a reply to it being
        // ingested as a letter -- see mail.js.
        from: mailFrom(POST_ADDRESS),
        to: recipient,
        replyTo: HUMAN_ADDRESS,
        subject: body.subject,
        text: body.text,
        html: body.html,
        headers: {
            'Auto-Submitted': 'auto-replied',
            ...(messageId ? { 'In-Reply-To': messageId, References: messageId } : {})
        },
        log
    });

    await recordDelivery({ tables, email: recipient, status: result.status, slug, now, log });

    log.info?.('ack: sent', { slug, status: result.status });
    return { status: result.status };
}
