// Copy the browser libraries out of node_modules and into web/vendor/.
//
// web/ has a package.json but no bundler and no build on deploy -- the Static
// Web App uploads the folder as it stands. So a dependency reaches a page only
// by being copied to a path a <script> tag can name, and this is what does the
// copying. npm resolves and locks the version; this picks the one file out of
// the package that the browser actually needs.
//
// The copies are committed rather than generated at deploy time, because the
// Function App needs them too -- functions/tools/sync-reader-assets.js copies
// them on again for the offline archive, and that deployment cannot reach
// outside functions/. Committed also means the exact bytes served are the exact
// bytes reviewed.
//
// Which makes drift the thing to be afraid of: Dependabot raises the version in
// package.json, nobody re-runs this, and the lock file claims one version while
// the site serves another. Hence --check, which the deploy workflow runs before
// it will upload anything.
//
//   node ../tools/vendor-web.js          from web/, or npm run vendor
//   node ../tools/vendor-web.js --check  compare only, exit 1 on a difference

import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const web = join(here, '..', 'web');
const modules = join(web, 'node_modules');
const vendor = join(web, 'vendor');

// Why each library is the file it is. This is the part a version bump cannot
// work out for itself: upstream can rename dist/umd/index.js, and the failure
// would otherwise be a missing script tag at runtime rather than here.
const NOTES = {
    'minisearch.js': [
        'The UMD build rather than the ESM one, and this is the one place the offline',
        'archive genuinely decides something: search has to work there -- an archive you',
        'cannot search is a folder of files -- and browsers refuse to load ES modules',
        'over file://, since the module fetch is subject to CORS and a file has no',
        'origin. UMD loads as a plain script in both places and puts MiniSearch on the',
        'global.'
    ],
    'wordcloud2.js': [
        'The package is UMD and puts WordCloud on the global, which is all a plain',
        'script tag needs. It ships no built file, so this is its source, which is what',
        'the published package intends -- the repository builds nothing else.'
    ]
};

const COPIES = [
    { package: 'minisearch', from: 'dist/umd/index.js', to: 'minisearch.js', header: true, license: 'LICENSE-minisearch.txt' },
    { package: 'minisearch', from: 'LICENSE.txt', to: 'LICENSE-minisearch.txt' },
    { package: 'wordcloud', from: 'src/wordcloud2.js', to: 'wordcloud2.js', header: true, license: 'LICENSE-wordcloud2.txt' },
    { package: 'wordcloud', from: 'LICENSE', to: 'LICENSE-wordcloud2.txt' },

    // Two stylesheets and one font out of a package that ships six families.
    // Only the brands are used -- the rest of the site's icons are drawn as
    // inline SVG -- and shipping the other five webfonts would be a megabyte of
    // glyphs nothing references.
    { package: '@fortawesome/fontawesome-free', from: 'css/fontawesome.min.css', to: 'fontawesome/css/fontawesome.min.css' },
    { package: '@fortawesome/fontawesome-free', from: 'css/brands.min.css', to: 'fontawesome/css/brands.min.css' },
    { package: '@fortawesome/fontawesome-free', from: 'webfonts/fa-brands-400.woff2', to: 'fontawesome/webfonts/fa-brands-400.woff2' },
    { package: '@fortawesome/fontawesome-free', from: 'LICENSE.txt', to: 'fontawesome/LICENSE.txt' }
];

const manifestOf = (name) =>
    JSON.parse(readFileSync(join(modules, name, 'package.json'), 'utf8'));

// Written into the file rather than kept in a table somewhere, so that anyone
// opening the copy can see what it is and that editing it is pointless. The
// licence and the home page are read from the package rather than restated
// here, because a restated licence is one that can silently stop being true.
function headerFor({ package: name, from, to, license }) {
    const manifest = manifestOf(name);
    const home = manifest.homepage ?? manifest.repository?.url ?? manifest.repository;
    const lines = [
        `${name} v${manifest.version} -- vendored, unmodified, from the npm package's ${from}.`,
        `${home}  ${manifest.license}, see ${license} beside this file.`,
        '',
        'Generated by tools/vendor-web.js from web/node_modules. Do not edit: run',
        '`npm run vendor` in web/ instead, and change the version in web/package.json.',
        '',
        ...NOTES[to]
    ];

    return `${lines.map((line) => (line ? `// ${line}` : '//')).join('\n')}\n`;
}

function contentsFor(copy) {
    const source = join(modules, copy.package, copy.from);

    return copy.header
        ? Buffer.from(headerFor(copy) + readFileSync(source, 'utf8'))
        : readFileSync(source);
}

const checking = process.argv.includes('--check');
const stale = [];

for (const copy of COPIES) {
    const target = join(vendor, copy.to);
    const wanted = contentsFor(copy);

    if (checking) {
        let found = null;
        try {
            found = readFileSync(target);
        } catch {
            // Missing counts as stale, which is what an unrun copy step looks
            // like on a fresh checkout of a Dependabot branch.
        }

        if (!found?.equals(wanted)) stale.push(copy.to);
        continue;
    }

    mkdirSync(dirname(target), { recursive: true });
    copy.header ? writeFileSync(target, wanted) : copyFileSync(join(modules, copy.package, copy.from), target);
    console.log(`${copy.package}/${copy.from} -> web/vendor/${copy.to}`);
}

if (!checking) {
    console.log(`\n${COPIES.length} files vendored. Remember functions/tools/sync-reader-assets.js.`);
} else if (stale.length) {
    console.error('web/vendor is out of date with web/package-lock.json:\n');
    for (const name of stale) console.error(`  ${name}`);
    console.error('\nRun `npm run vendor` in web/, then `node tools/sync-reader-assets.js` in functions/.');
    process.exit(1);
} else {
    console.log(`${COPIES.length} vendored files match node_modules.`);
}
